/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.jsx'],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        canvas: '#0B0D0F',
        surface: '#121518',
        'surface-container-low': '#121518',
        'surface-container': '#171B1F',
        'surface-container-high': '#181C20',
        'surface-container-highest': '#1C2127',
        hairline: '#232830',
        'on-surface': '#F1F3F5',
        'on-surface-variant': '#94A0B8',
        outline: '#4B5565',
        primary: '#D97706',
        'primary-hover': '#B45309',
        'on-primary': '#0B0D0F',
        secondary: '#10B981',
        'on-secondary': '#0B0D0F',
        tertiary: '#F43F5E',
        'on-tertiary': '#0B0D0F',
      },
      fontFamily: {
        sans: ['Geist', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '38px', fontWeight: '600' }],
        'display-lg-mobile': ['26px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '26px', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '22px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'stat-lg': ['28px', { lineHeight: '32px', fontWeight: '500' }],
        'stat-lg-mobile': ['22px', { lineHeight: '26px', fontWeight: '500' }],
        'stat-md': ['15px', { lineHeight: '20px', fontWeight: '500' }],
        'label-mono': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'label-sans': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        gutter: '1rem',
        'gutter-desktop': '1.5rem',
        margin: '1rem',
        'margin-tablet': '2rem',
        'margin-desktop': '3rem',
      },
    },
  },
  plugins: [],
}
